CREATE TABLE IF NOT EXISTS client_anamnesis (
  ClientId INT NOT NULL,
  BirthDate DATE NULL,
  Occupation VARCHAR(100) NULL,
  Phone VARCHAR(30) NULL,
  RG VARCHAR(30) NULL,
  CPF VARCHAR(30) NULL,
  ShoeType VARCHAR(50) NULL,
  SockType VARCHAR(50) NULL,
  BladeType VARCHAR(50) NULL,
  HasSomeoneCareNails TINYINT(1) NULL,
  HasSomeoneCareCuticles TINYINT(1) NULL,
  BitesNails TINYINT(1) NULL,
  Medication VARCHAR(255) NULL,
  HasPainSensitivity TINYINT(1) NULL,
  HasDiabetes TINYINT(1) NULL,
  DiabetesType VARCHAR(100) NULL,
  HasAllergy TINYINT(1) NULL,
  AllergyDetails VARCHAR(255) NULL,
  HasHypertension TINYINT(1) NULL,
  HadSurgery TINYINT(1) NULL,
  SurgeryDetails VARCHAR(255) NULL,
  HasInfectiousDisease TINYINT(1) NULL,
  InfectiousDiseaseDetails VARCHAR(255) NULL,
  HasVascularDisease TINYINT(1) NULL,
  VascularDiseaseDetails VARCHAR(255) NULL,
  UsesAnticoagulant TINYINT(1) NULL,
  HasThyroidCondition TINYINT(1) NULL,
  IsPregnant TINYINT(1) NULL,
  PregnancyWeeks INT NULL,
  UnderMedicalTreatment TINYINT(1) NULL,
  MedicalSpecialty VARCHAR(255) NULL,
  HasCramps TINYINT(1) NULL,
  HasVarices TINYINT(1) NULL,
  OtherSymptoms TEXT NULL,
  ObservationsLeftFoot TEXT NULL,
  ObservationsRightFoot TEXT NULL,
  ProfessionalNotes TEXT NULL,
  HasOnychomycosis TINYINT(1) NULL,
  HasDermatophytosis TINYINT(1) NULL,
  HasParonychia TINYINT(1) NULL,
  HasDystrophy TINYINT(1) NULL,
  HasTorque TINYINT(1) NULL,
  PRIMARY KEY (ClientId),
  CONSTRAINT fk_client_anamnesis_client FOREIGN KEY (ClientId)
    REFERENCES client (Id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
